export const ERROR_CONFIG = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED_REQUEST',
  REQUIRED: 'CREDENTIALS_REQUIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BODY_REQUIRED: 'BODY_REQUIRED',
};
